export let NotificationType = {
    FAIL :{
        PLAYER_NOT_FOUND: 'Player Not Found',
        PLAYER_IS_OFFLINE: 'Player Is Offline',
        ROOM_IS_FULL: 'Room Is Full',
        TOKEN_NOT_FOUND: 'Token Not Found',
        TOKEN_NOT_IS_VALID: 'Token Not Is Valid',
        USER_NOT_FOUND: 'User Not Found',
    },
}


export let defaultConfig= [
    {id: 0, cn:'br'},
    {id: 1, cn:'bn'},
    {id: 2, cn:'bb'},
    {id: 3, cn:'bq'},
    {id: 4, cn:'bk'},
    {id: 5, cn:'bp'},
    {id: 6, cn:'bn'},
    {id: 7, cn:'br'},
    {id: 8, cn:'bp'},
    {id: 9, cn:'bp'},
    {id: 10, cn:'bp'},
    {id: 11, cn:'bp'},
    {id: 12, cn:'bp'},
    {id: 13, cn:'bp'},
    {id: 14, cn:'bp'},
    {id: 15, cn:'bp'},
    {id:48, cn:'wp'},
    {id:49, cn:'wp'},
    {id:50, cn:'wp'},
    {id:51, cn:'wp'},
    {id:52, cn:'wp'},
    {id:53, cn:'wp'},
    {id:54, cn:'wp'},
    {id:55, cn:'wp'},
    {id:56, cn:'wr'},
    {id:57, cn:'wn'},
    {id:58, cn:'wb'},
    {id:59, cn:'wq'},
    {id:60, cn:'wk'},
    {id:61, cn:'wb'},
    {id:62, cn:'wn'},
    {id:63, cn:'wr'},
]